name: PlatformIO Release

on: 
#  release:
#    types: [published]
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Cache pip
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: pip install platformio==6.1.5
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 18
    - name: Archive built firmware image
      uses: actions/upload-artifact@v4
      with:
        name: firmware.bin
        path: .pio/build/nodemcuv2/firmware.bin
    - name: Run PlatformIO
      # run: pio run -e <ID_1> -e <ID_2> -e <ID_N>
      run: pio run
    - name: Release
      uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      with:
        artifacts: ".pio/build/nodemcuv2/firmware.bin"

