name: PlatformIO Release

on: 
#  release:
#    types: [published]
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Cache pip
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: pip install platformio==6.1.5
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 18
    - name: Archive built firmware image
      uses: actions/upload-artifact@v4
      with:
        name: firmware.bin
        path: .pio/build/nodemcuv2/firmware.bin
    - name: Run PlatformIO
      # run: pio run -e <ID_1> -e <ID_2> -e <ID_N>
      run: pio run
    - name: Release
      uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      with:
        artifacts: ".pio/build/nodemcuv2/firmware.bin"

