name: PlatformIO CI

on: 
#  release:
#    types: [published]
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Setup PlatformIO
      uses: n-vr/setup-platformio-action@v1
      with:
        platformio-version: "6.1.5"
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Run PlatformIO
      # run: pio run -e <ID_1> -e <ID_2> -e <ID_N>
      run: pio run
    - name: Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: ".pio/build/nodemcuv2/firmware.bin"

