name: PlatformIO Release

on: 
#  release:
#    types: [published]
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Cache pip
      uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: pip install platformio==6.1.5
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: 18
    - name: Archive built firmware image
      uses: actions/upload-artifact@v4
      with:
        name: firmware.bin
        path: .pio/build/nodemcuv2/firmware.bin
    - name: Run PlatformIO
      # run: pio run -e <ID_1> -e <ID_2> -e <ID_N>
      run: pio run
    - name: Release
      uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      with:
        artifacts: ".pio/build/nodemcuv2/firmware.bin"

