name: PlatformIO Release

on: 
#  release:
#    types: [published]
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Cache pip
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: pip install platformio==6.1.5
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 18
    - name: Archive built firmware image
      uses: actions/upload-artifact@v4
      with:
        name: firmware.bin
        path: .pio/build/nodemcuv2/firmware.bin
    - name: Run PlatformIO
      # run: pio run -e <ID_1> -e <ID_2> -e <ID_N>
      run: pio run
    - name: Release
      uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
      with:
        artifacts: ".pio/build/nodemcuv2/firmware.bin"

