name: PlatformIO CI

on: 
  push:
  schedule:
  # each first day of month
  - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Setup PlatformIO
      uses: n-vr/setup-platformio-action@v1
#      with:
#        platformio-version: "6.1.4"
#    - uses: actions/setup-node@v3
#      with:
#        node-version: 14 # npm dependency resolution for esp8266 iot framework breaks with 16
    - name: Run PlatformIO
      # run: pio run -e <ID_1> -e <ID_2> -e <ID_N>
      run: pio run
